# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8615892d548df495f783a9bd75d746a58f30ed495398da6633e02854f172eacfc2e5ae070e3fe24d561154dccfb6e4fa7405160f1d0b8429d629ace6ad528f5

test:
  secret_key_base: 8b4cf35bec60c0f3075dbd2eef41f6399698fbb93d14e947d4b2547eec003f90f41669b271548f26095766cd8a0d5abec3ccf6f350608233e925f62f2f9d346e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
